#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "archivebox"
name = "ArchiveBox"
description.en = "Archiving solution to collect, save, and view sites you want to preserve offline"
description.fr = "Solution d'archivage pour collecter, enregistrer et afficher les sites que vous souhaitez conserver hors ligne"

version = "0.7.4~ynh1"

maintainers = ["Max Fowler"]

[upstream]
license = "MIT"
website = "https://archivebox.io/"
demo = "https://archiveboxdemo.commoninternet.net"
admindoc = "https://github.com/ArchiveBox/ArchiveBox/wiki"
code = "https://github.com/ArchiveBox/ArchiveBox"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    help.en = "If true, saved archives will be viewable without logging in."
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Choose a password that is different from the username and does not contain the `$` symbol."
    help.fr = "Choisissez judicieusement un mot de passe différent du nom d'utilisateur et ne contenant pas le symbole `$`."
    type = "password"

[resources]
    [resources.sources.main]
    url = "https://github.com/ArchiveBox/ArchiveBox/archive/refs/tags/v0.7.4.tar.gz"
    sha256 = "75ed23741f1198d19e77b7adc7a73184683912450b16535a27c9e1695230086b"
    autoupdate.strategy = "latest_github_release"


    [resources.sources.uv]
    amd64.url = "https://github.com/astral-sh/uv/releases/download/0.11.21/uv-x86_64-unknown-linux-gnu.tar.gz"
    amd64.sha256 = "8c88519b0ef0af9801fcdee419bbb12116bd9e6b18e162ae093c932d8b264050"
    arm64.url = "https://github.com/astral-sh/uv/releases/download/0.11.21/uv-aarch64-unknown-linux-gnu.tar.gz"
    arm64.sha256 = "88e800834007cc5efd4675f166eb2a51e7e3ad19876d85fa8805a6fb5c922397"
    armhf.url = "https://github.com/astral-sh/uv/releases/download/0.11.21/uv-armv7-unknown-linux-gnueabihf.tar.gz"
    armhf.sha256 = "929440f991ccd8097e01be1ec831f673ac7bbf508e94819b4270f2873f69e658"

    in_subdir = true
    
    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/astral-sh/uv"
    autoupdate.asset.amd64 = "^uv-x86_64-unknown-linux-gnu.tar.gz"
    autoupdate.asset.arm64 = "^uv-aarch64-unknown-linux-gnu.tar.gz"
    autoupdate.asset.armhf = "^uv-armv7-unknown-linux-gnueabihf.tar.gz"


    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"
    
    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
	
    
    [resources.apt]
packages = [
    "libldap2-dev",
    "libsasl2-dev",
    "libssl-dev",
    "python3-venv",
    "expect",
    "apt-transport-https",
    "ca-certificates",
    "gnupg2",
    "zlib1g-dev",
    "dumb-init",
    "gosu",
    "unzip",
    "curl",
    "wget",
    "fontconfig",
    "fonts-ipafont-gothic",
    "fonts-wqy-zenhei",
    "fonts-thai-tlwg",
    "fonts-symbola",
    "fonts-noto",
    "fonts-freefont-ttf",
    "chromium",
    "ffmpeg",
    "yt-dlp",
    "ripgrep",
    "build-essential",
    "python3-dev",
    ]
packages_from_raw_bash = """
    if [[ $YNH_DEBIAN_VERSION == "bookworm" ]]; then
        echo "fonts-kacst";
    elif [[ $YNH_DEBIAN_VERSION == "trixie" ]]; then
        echo "fonts-kacst-one";
    fi
    """

	
    [resources.nodejs]
    version = "22"
    
