#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.235a374399c4a1e144873e58828555840209f415.name = "Upgrade from 0.7.3~ynh1"
    #test_upgrade_from.719751ec9342e287d65f159349217fe0d498c294.name = "Upgrade from 0.6.2"
