#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent;
location __PATH__/ {

  proxy_set_header Accept-Encoding "";
  proxy_pass http://127.0.0.1:__PORT__;
  include proxy_params_no_auth;
  proxy_set_header Proxy "";
  proxy_pass_header Server;
}
