#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STORE SETTINGS
#=================================================

python_version=3.11

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Stopping a systemd service..." 

ynh_systemctl --service="$app" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep=".venv .uv .uv_cache .python_runtime"
chown -R "$app:www-data" "$install_dir"

#=================================================
# UPGRADE UV
#=================================================
ynh_script_progression --message="Upgrading uv..."

ynh_setup_source --dest_dir="$install_dir/.uv" --source_id="uv"
chmod +x "$install_dir/.uv/uv"

export PATH="$install_dir/.uv:$PATH"
export UV_PYTHON_INSTALL_DIR="$install_dir/.python_runtime"
export UV_CACHE_DIR="$install_dir/.uv_cache"

#=================================================
# UPGRADE UV PROJECT
#=================================================
ynh_script_progression --message="Upgrading $app's dependencies..."


ynh_hide_warnings uv sync --no-dev --python "$python_version" --project "$install_dir"
chown -R "$app:" "$install_dir"

archivebox_cmd="$install_dir/.venv/bin/archivebox"

#=================================================
# UPGRADE NODE DEPENDENCIES
#=================================================
ynh_script_progression --message="Upgrading node dependencies..."

pushd "$install_dir"
    ynh_hide_warnings npm ci
popd

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression --message="Updating a configuration file..." 

ynh_add_config --template="ArchiveBox.conf" --destination="$data_dir/ArchiveBox.conf"

chmod 600 "$data_dir/ArchiveBox.conf"
chown $app:$app "$data_dir/ArchiveBox.conf"

#=================================================
# FINISH ARCHIVEBOX SETUP
#=================================================

# rerun archivebox setup (its idempotent, so it should be ok during upgrade)
ynh_script_progression --message="Finishing Archivebox Setup" 

pushd "$data_dir"
    ynh_hide_warnings ynh_exec_as_app $archivebox_cmd init --setup
popd

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Upgrading system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

# Use logrotate to manage app-specific logfile(s)
ynh_config_add_logrotate

yunohost service add $app --description="Self-hosted internet archiving" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." 

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" 
